component:
    id: 1
benchmark:
    type: 7
    relativeUrl: /
sourceCode:
    entryPoint: public/index.php
    urls:
        jsonSerialization: 'https://github.com/phpbenchmarks/php/tree/5.6.40_json-serialization-hello-world_0/public/index.php#L13'
        integerSerialization: 'https://github.com/phpbenchmarks/php/tree/5.6.40_json-serialization-hello-world_0/public/index.php#L13'
        floatSerialization: 'https://github.com/phpbenchmarks/php/tree/5.6.40_json-serialization-hello-world_0/public/index.php#L13'
        stringSerialization: 'https://github.com/phpbenchmarks/php/tree/5.6.40_json-serialization-hello-world_0/public/index.php#L13'
        booleanSerialization: 'https://github.com/phpbenchmarks/php/tree/5.6.40_json-serialization-hello-world_0/public/index.php#L13'
        nullSerialization: 'https://github.com/phpbenchmarks/php/tree/5.6.40_json-serialization-hello-world_0/public/index.php#L13'
        arraySerialization: 'https://github.com/phpbenchmarks/php/tree/5.6.40_json-serialization-hello-world_0/public/index.php#L13'
        objectSerialization: 'https://github.com/phpbenchmarks/php/tree/5.6.40_json-serialization-hello-world_0/public/index.php#L13'
coreDependency:
    name: php
    version: 5.6.40
