component:
    slug: php
benchmark:
    type: hello-world
    relativeUrl: /
sourceCode:
    entryPoint: public/index.php
    urls:
        entryPoint: 'https://github.com/phpbenchmarks/php/blob/8.1.0_hello-world_0/public/index.php'
coreDependency:
    name: php
    version: 8.1.0
