component:
    id: 1
benchmark:
    type: 3
    relativeUrl: /
sourceCode:
    entryPoint: public/index.php
    urls:
        entryPoint: 'https://github.com/phpbenchmarks/php/tree/5.6.40_hello-world_0/public/index.php'
        randomizeLanguageDispatchEvent: 'https://github.com/phpbenchmarks/php/tree/5.6.40_hello-world_0/public/index.php#L52'
        randomizeLanguageEventListener: 'https://github.com/phpbenchmarks/php/tree/5.6.40_hello-world_0/src/Translation/TranslationService.php#L9'
        translations: 'https://github.com/phpbenchmarks/php/tree/5.6.40_hello-world_0/translations/phpbenchmarks.en_GB.php'
        translate: 'https://github.com/phpbenchmarks/php/tree/5.6.40_hello-world_0/public/index.php#L18'
        serialize: 'https://github.com/phpbenchmarks/php/tree/5.6.40_hello-world_0/public/index.php#L59'
coreDependency:
    name: php
    version: 5.6.40
