component:
    slug: php
benchmark:
    type: json-serialization-big-overload
    relativeUrl: /
sourceCode:
    entryPoint: public/index.php
    urls:
        jsonSerialization: 'https://github.com/phpbenchmarks/php/tree/8.0.0_json-serialization-big-overload_0/public/index.php#L15'
        integerSerialization: 'https://github.com/phpbenchmarks/php/tree/8.0.0_json-serialization-big-overload_0/public/index.php#L15'
        floatSerialization: 'https://github.com/phpbenchmarks/php/tree/8.0.0_json-serialization-big-overload_0/public/index.php#L15'
        stringSerialization: 'https://github.com/phpbenchmarks/php/tree/8.0.0_json-serialization-big-overload_0/public/index.php#L15'
        booleanSerialization: 'https://github.com/phpbenchmarks/php/tree/8.0.0_json-serialization-big-overload_0/public/index.php#L15'
        nullSerialization: 'https://github.com/phpbenchmarks/php/tree/8.0.0_json-serialization-big-overload_0/public/index.php#L15'
        arraySerialization: 'https://github.com/phpbenchmarks/php/tree/8.0.0_json-serialization-big-overload_0/public/index.php#L15'
        objectSerialization: 'https://github.com/phpbenchmarks/php/tree/8.0.0_json-serialization-big-overload_0/public/index.php#L15'
coreDependency:
    name: php
    version: 8.0.0
