component:
    id: 1
benchmark:
    type: 4
    relativeUrl: /
sourceCode:
    entryPoint: public/index.php
    urls:
        template: 'https://github.com/phpbenchmarks/php/tree/7.2.27_templating-small-overload_0/public/index.php'
        templatingLayout: 'https://github.com/phpbenchmarks/php/tree/7.2.27_templating-small-overload_0/public/index.php#L6'
        templatingBlocks: 'https://github.com/phpbenchmarks/php/tree/7.2.27_templating-small-overload_0/templates/layout/layout_start.php#L31'
        templatingFunctions: 'https://github.com/phpbenchmarks/php/tree/7.2.27_templating-small-overload_0/public/index.php#L8'
        templatingMacros: 'https://github.com/phpbenchmarks/php/tree/7.2.27_templating-small-overload_0/public/index.php#L432'
        templatingEscapeStringHtml: 'https://github.com/phpbenchmarks/php/tree/7.2.27_templating-small-overload_0/public/index.php#856'
        templatingEscapeStringJs: 'https://github.com/phpbenchmarks/php/tree/7.2.27_templating-small-overload_0/public/index.php#2877'
        templatingVariables: 'https://github.com/phpbenchmarks/php/tree/7.2.27_templating-small-overload_0/public/index.php#L5933'
        templatingOutputRaw: 'https://github.com/phpbenchmarks/php/tree/7.2.27_templating-small-overload_0/public/index.php#L5933'
        templatingOutputUnknownVariables: 'https://github.com/phpbenchmarks/php/tree/7.2.27_templating-small-overload_0/public/index.php#L6855'
        templatingOutputMethodCalls: 'https://github.com/phpbenchmarks/php/tree/7.2.27_templating-small-overload_0/public/index.php#L7277'
        templatingIncludeTemplates: 'https://github.com/phpbenchmarks/php/tree/7.2.27_templating-small-overload_0/public/index.php#L9308'
coreDependency:
    name: php
    version: 7.2.27
